# ------------------------------------------------------------------
# Brobond AI Commerce OS — Production Dockerfile
# Multi-stage build targeting Next.js standalone output.
# ------------------------------------------------------------------

# --- Stage 1: dependencies (full, incl. devDependencies) ----------
FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
COPY package.json package-lock.json* ./
RUN npm ci

# --- Stage 2: build -----------------------------------------------
FROM node:20-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Prisma client is generated by the `build` script (prisma generate && next build)
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# --- Stage 2b: production dependency closure ----------------------
# The `preDeployCommand`/entrypoint runs `prisma migrate deploy`, which loads
# prisma.config.ts -> @prisma/config -> effect -> fast-check. Those packages
# (and the rest of the Prisma CLI's transitive closure, including hoisted deps
# such as fast-check, pure-rand and empathic) must be present in the runner.
#
# Rather than hand-copy an ever-incomplete list of individual packages — the
# exact bug this fixes, where the hoisted `fast-check` was omitted and the CLI
# died with "Cannot find module 'fast-check'" — resolve the FULL production
# tree the way npm does and copy it wholesale. `npm ci --omit=dev` reproduces
# the same tree Render builds for `preDeployCommand`, so the image matches the
# platform exactly and cannot drift out of sync with the lock file.
FROM node:20-alpine AS proddeps
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

# --- Stage 3: runtime ---------------------------------------------
FROM node:20-alpine AS runner
WORKDIR /app
RUN apk add --no-cache openssl
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Standalone server + static assets + Prisma runtime artifacts.
# Prisma's client engine uses query_compiler_bg.wasm even with engineType
# ="client". Next standalone tracing does not reliably include this generated
# binary, so copy the generated .prisma directory explicitly. Without it the
# first database operation fails at runtime with ENOENT.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts

# Migration tooling — the COMPLETE production dependency tree.
#
# The standalone bundle contains the SERVER only, so the Prisma CLI was not in
# the image at all: the container booted straight into `node server.js`
# against a database that had never been migrated, and every request that
# touched Prisma failed with PostgreSQL 42P01, relation "_prisma_migrations"
# does not exist.
#
# The earlier fix copied a hand-maintained list of individual CLI packages,
# but that list re-implemented npm's dependency resolution by hand and drifted
# out of sync: `fast-check` (a dependency of `effect`, itself required by
# `@prisma/config`) is HOISTED to the top level and was never copied, so the
# CLI died loading prisma.config.ts with:
#
#   Error: Cannot find module 'fast-check'
#   Require stack: @prisma/config -> effect -> fast-check
#
# Copy the full `npm ci --omit=dev` tree instead. It is exactly what Render
# installs for the `preDeployCommand`, it always contains the Prisma CLI plus
# its complete transitive closure (@prisma/config, effect, fast-check,
# pure-rand, empathic, the pg driver, the TypeScript/jiti loader for the .ts
# config, …), and it can never drift from the lock file. The standalone
# node_modules is copied first (server runtime), then overlaid with the
# production tree so migration tooling is guaranteed present.
COPY --from=proddeps --chown=nextjs:nodejs /app/node_modules ./node_modules
# Prisma's client engine uses query_compiler_bg.wasm even with
# engineType="client". Next standalone tracing does not reliably include this
# generated binary, so copy the generated .prisma directory explicitly (after
# the production tree so it is not overwritten). Without it the first database
# operation fails at runtime with ENOENT.
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma

COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod 0755 /usr/local/bin/docker-entrypoint.sh

USER nextjs
EXPOSE 3000
# Applies every pending migration, then execs the Next.js server.
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
